#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import InstancesHandler, CoapError


class InstancesHandler_15002(InstancesHandler):
    EXTERNAL_NOTIFY = False

    def create(self,
               instance_id):  # int
        # TODO: create new instance
        #raise CoapError.NOT_IMPLEMENTED
        pass

    def delete(self,
               instance_id):  # int
        # TODO: delete instance
        # TODO: raise CoapError.BAD_REQUEST if instance does not exist
        #raise CoapError.NOT_IMPLEMENTED
        pass

    def list(self):
        # TODO: print space-separated list of existing instances to stdout
        print("0 1 2 3")


if __name__ == '__main__':
    InstancesHandler_15002().main()
