#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_8_4(ResourceHandler):
    NAME = "Wipe target"
    DESCRIPTION = '''\
To specify one or several targets for the wipe operation. This allows
 * selecting specific data, or, memory areas for the wipe operation.'''
    DATATYPE = DataType.STRING

    def write(self,
              instance_id,            # int
              resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: read value from stdin
        raise CoapError.NOT_IMPLEMENTED

    def reset(self,
              instance_id):  # int
        # TODO: reset resource to its original state. You can either clear it to
        # have 0 resource instances or delete the resource altogether.
        raise CoapError.NOT_IMPLEMENTED

    def list(self,
             instance_id):  # int
        # TODO: print space-separated list of available Resource Instance IDs
        raise CoapError.NOT_IMPLEMENTED


if __name__ == '__main__':
    ResourceHandler_8_4().main()
