#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_15003_26242(ResourceHandler):
    NAME = "Gateway ID"
    DESCRIPTION = '''Unique gateway ID.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        print(1)


if __name__ == '__main__':
    ResourceHandler_15003_26242().main()
