#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import json
import sys


class ResourceHandler_15003_26243(ResourceHandler):
    NAME = "Channel plan"
    DESCRIPTION = '''Frequency plans for various regions.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        print("eu-868")

    def write(self,
              instance_id,            # int
              resource_instance_id):  # int for multiple resources, None otherwise
        pass

if __name__ == '__main__':
    ResourceHandler_15003_26243().main()
