#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import sys
import json


class ResourceHandler_15003_26246(ResourceHandler):
    NAME = "Packets RX"
    DESCRIPTION = '''Number of LoRa packets received from device.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        with open("/etc/svetovid/dm/15003/config.json", "r") as configFile:
           file = json.load(configFile)
           path = file["PACKET_STATS"]
        with open(path, "r") as loRaConfig:
           packetStats = json.load(loRaConfig)
           print(packetStats["PACKET_RX"])

if __name__ == '__main__':
    ResourceHandler_15003_26246().main()
