#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import json
import sys


class ResourceHandler_15003_26244(ResourceHandler):
    NAME = "Channel frequency"
    DESCRIPTION = '''Defines radio frequency for each of 8 channels'''
    DATATYPE = DataType.FLOAT

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise

        if resource_instance_id == 0:
            with open("/etc/svetovid/dm/15003/config.json", "r") as configFile:
                file = json.load(configFile)
                path = file["CONFIG_PATH"]
            with open(path, "r") as loRaConfig:
                config = json.load(loRaConfig)
                print(config["carrier_frequency_mhz"])
        else:
            print(0.0)

    def write(self,
              instance_id,            # int
              resource_instance_id):  # int for multiple resources, None otherwise

        if resource_instance_id == 0:
            with open("/etc/svetovid/dm/15003/config.json", "r") as configFile:
                file = json.load(configFile)
                path = file["CONFIG_PATH"]
            with open(path, "r") as loRaConfig:
                config = json.load(loRaConfig)
                config["carrier_frequency_mhz"] = float(sys.stdin.read())
            with open(path, "w") as jsonFile:
                json.dump(config, jsonFile)
        else:
            pass

    def list(self,
             instance_id):
        # TODO: print space-separated list of existing instances to stdout
        print("0 1 2 3 4 5 6 7")

if __name__ == '__main__':
    ResourceHandler_15003_26244().main()
