#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import json
import sys


class ResourceHandler_15003_26251(ResourceHandler):
    NAME = "Spreading Factor"
    DESCRIPTION = '''The spreading factor controls the chirp rate,
and thus controls the speed of data transmission.
Lower spreading factors mean faster chirps
and therefore a higher data transmission rate.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        with open("/etc/svetovid/dm/15003/config.json", "r") as configFile:
            file = json.load(configFile)
            path = file["CONFIG_PATH"]
        with open(path, "r") as loRaConfig:
            config = json.load(loRaConfig)
            print(config["spreading_factor"])

    def write(self,
              instance_id,            # int
              resource_instance_id):  # int for multiple resources, None otherwise
        with open("/etc/svetovid/dm/15003/config.json", "r") as configFile:
           file = json.load(configFile)
           path = file["CONFIG_PATH"]
        with open(path, "r") as loRaConfig:
           config = json.load(loRaConfig)
           config["spreading_factor"] = int(sys.stdin.read())
        with open(path, "w") as jsonFile:
           json.dump(config, jsonFile)

if __name__ == '__main__':
    ResourceHandler_15003_26251().main()
