#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_1(ResourceHandler):
    NAME = "Model Number"
    DESCRIPTION = '''\
A model identifier (manufacturer specified string)'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        print("🍓")




if __name__ == '__main__':
    ResourceHandler_3_1().main()
