#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_15(ResourceHandler):
    NAME = "Timezone"
    DESCRIPTION = '''\
Indicates in which time zone the LwM2M Device is located, in IANA
 * Timezone (TZ) database format.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print("TODO")


    def write(self,
              instance_id,            # int
              resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: read value from stdin
        raise CoapError.NOT_IMPLEMENTED

    def reset(self,
              instance_id):  # int
        # TODO: reset resource to its original state. You can either set it to
        # a default value or delete the resource.
        pass



if __name__ == '__main__':
    ResourceHandler_3_15().main()
