#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_17(ResourceHandler):
    NAME = "Device Type"
    DESCRIPTION = '''\
Type of the device (manufacturer specified string: e.g. smart meters /
 * dev Class / ...)'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print("TODO")




if __name__ == '__main__':
    ResourceHandler_3_17().main()
