#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_21(ResourceHandler):
    NAME = "Memory Total"
    DESCRIPTION = '''\
Total amount of storage space which can store data and software in the
 * LwM2M Device (expressed in kilobytes).  Note: 1 kilobyte corresponds
 * to 1000 bytes.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0)




if __name__ == '__main__':
    ResourceHandler_3_21().main()
