#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_3(ResourceHandler):
    NAME = "Firmware Version"
    DESCRIPTION = '''\
Current firmware version of the Device.The Firmware Management
 * function could rely on this resource.'''
    DATATYPE = DataType.STRING
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        print("21.12-raspberry")




if __name__ == '__main__':
    ResourceHandler_3_3().main()
