#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore
import os

class ResourceHandler_3_4(ResourceHandler):
    NAME = "Reboot"
    DESCRIPTION = '''\
Reboot the LwM2M Device to restore default LoRa configuration'''

    def execute(self,
                instance_id,  # int
                args):        # int -> (str or None)
        os.system("cp /home/admin/workspace/LoRaPacketForwarder/config_copy.json /home/admin/workspace/LoRaPacketForwarder/config.json")



if __name__ == '__main__':
    ResourceHandler_3_4().main()
