#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_7(ResourceHandler):
    NAME = "Power Source Voltage"
    DESCRIPTION = '''\
Present voltage for each Available Power Sources Resource Instance.
 * The unit used for this resource is in mV.'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0)


    def list(self,
             instance_id):  # int
        # TODO: print space-separated list of available Resource Instance IDs
        raise CoapError.NOT_IMPLEMENTED


if __name__ == '__main__':
    ResourceHandler_3_7().main()
