#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

from fsdm import ResourceHandler, CoapError, DataType, KvStore


class ResourceHandler_3_9(ResourceHandler):
    NAME = "Battery Level"
    DESCRIPTION = '''\
Contains the current battery level as a percentage (with a range from
 * 0 to 100). This value is only valid for the Device internal Battery if
 * present (one Available Power Sources Resource Instance is 1).'''
    DATATYPE = DataType.INTEGER
    EXTERNAL_NOTIFY = False

    def read(self,
             instance_id,            # int
             resource_instance_id):  # int for multiple resources, None otherwise
        # TODO: print value to stdout
        print(0)




if __name__ == '__main__':
    ResourceHandler_3_9().main()
